name: Build, Push, and Deploy Wisecow

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t sagarpatade1900/wisecow:latest .
        docker push sagarpatade1900/wisecow:latest

  setup_minikube:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Minikube
      uses: medyagh/setup-minikube@latest
      with:
        minikube-version: '1.34.0'
        driver: 'docker'
        container-runtime: 'containerd'
        kubernetes-version: 'v1.32.0'
        cpus: '4'
        memory: '4000m'
        addons: 'ingress,dashboard'

    - name: Load Docker image into Minikube
      run: |
        minikube image load sagarpatade1900/wisecow:latest

  deploy:
    runs-on: ubuntu-latest
    needs: setup_minikube
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Configure kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        kubectl rollout status deployment/wisecow-deployment
